# Node Image for docker on which code will execute
include:
  template: Dependency-Scanning.gitlab-ci.yml

image: registry.gitlab.com/mastic/angular-cli:latest

stages:
  - build
  - test
  - sonar-check
  - upload
  - deploy
  
before_script:
  - npm install
variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"  
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - dist/  

.test:
  stage: test
  image: registry.gitlab.com/mastic/puppeteer:latest
  cache:
    policy: pull
  artifacts:
    untracked: true
    when: always
    expire_in: 1 week
    reports:
      junit: report/test/TESTS-*.xml

test_code:
  stage: test
  extends: .test
  script:
  - npm run test-ci
  only: ['master']

sonarcloud-check:
  stage: sonar-check
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - master  

build_master:
  image: node:4.2.2
  stage: build
  script:
  - npm run build --prod
  only: ['master']

upload_artifact_code:
  stage: upload
  image: "python:latest"
  before_script:
    - pip install awscli
  script:
  - aws s3 cp dist/ s3://$S3_BUCKET/ --recursive --include "*"
  only: ['master']