pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'

- task: CmdLine@2
  displayName: 'build'
  inputs:
    script: |
      npm install -g @angular/cli
      npm install
      ng build --prod

- task: CmdLine@2
  displayName: 'Unit test'
  inputs:
    script: 'npm run test-ci'
   
- task: SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'danielavo'
    scannerMode: 'CLI'
    configMode: 'file'
