pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'

- task: CmdLine@2
  displayName: 'build'
  inputs:
    script: |
      npm install -g @angular/cli
      npm install
      ng build --prod

- task: CmdLine@2
  displayName: 'Unit test'
  inputs:
    script: 'npm run test-ci'
   
- task: SonarCloudPrepare@1
  displayName: 'Preparacion de analisis'
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'danielavo'
    scannerMode: 'CLI'

- task: SonarCloudAnalyze@1
  displayName: 'Analisis de codigo'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

