
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'

- task: Npm@1
  inputs:
    command: 'install'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run test-ci'
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonar-Cloud-Dani'
    organization: 'danielavo'
    scannerMode: 'MSBuild'
    projectKey: 'DanielaVO_pet-book'
- task: SonarCloudAnalyze@1

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build --prod'
