
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '6.x'
    checkLatest: true
- task: Npm@1
  inputs:
    command: 'install'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run test-ci'
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonar-Cloud'
    organization: 'valentinalenisudem'
    scannerMode: 'MSBuild'
    projectKey: 'pet-book-udem'
    projectName: 'pet-book-udem'
- task: SonarCloudAnalyze@1

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build --prod'
